---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cedge-service
  namespace: omec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cedge-service
  template:
    metadata:
      labels:
        app: cedge-service
    spec:
      containers:
        - name: cedge-service
          image: docker.io/802dot1q/service:v0.0.2
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 512Mi
              cpu: 500m
          ports:
            - containerPort: 8888
      nodeSelector:
        site: site2
---
apiVersion: v1
kind: Service
metadata:
  name: cedge-service
  namespace: omec
spec:
  type: NodePort
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
      nodePort: 30010
  selector:
    app: cedge-service
