---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cedge-api
  namespace: omec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cedge-api
  template:
    metadata:
      labels:
        app: cedge-api
    spec:
      containers:
        - name: cedge-api
          image: docker.io/802dot1q/cedge-api:v0.1.7
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 512Mi
              cpu: 500m
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: cedge-api
  namespace: omec
spec:
  ports:
    - port: 8080
      targetPort: 5000
  selector:
    app: cedge-api
